/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 heart.glb --transform 
Files: heart.glb [13.53MB] > heart-transformed.glb [1.17MB] (91%)
Author: lukinu (https://sketchfab.com/lukinu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/heart-in-glass-1dacc91d294141658633cce0a79ecd97
Title: Heart in glass
*/

import { useRef, useEffect, useState } from "react";
import { useGLTF, Outlines } from "@react-three/drei";

import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/heart.glb");
  const ref = useRef();
  const [hovered, hover] = useState(false);

  useFrame((state, delta) => {
    // ref.current.rotation.x = ref.current.rotation.y += delta;
    ref.current.position.y = -0.35 + Math.sin(state.clock.elapsedTime) / 15;
  });

  return (
    <group ref={ref} {...props} dispose={null} position={[0, -0.6, 0]}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.Coeur1}
        toneMapped={true}
      ></mesh>
      <mesh
        geometry={nodes.defaultMaterial_1.geometry}
        material={materials.Crystal}
        toneMapped={false}
      >
        {/* <Outlines thickness={0.05} color={"black"} /> */}
      </mesh>
    </group>
  );
}

useGLTF.preload("/heart.glb");
